jwt:
  secret:
    key: d348641f16ebb1db9b17382a4694fa59476d764a9914337d7cc6beeeae858a475ed6cfabbfe4551fe8b13e1b8d305bff74dff399d52632a9f8aff1bef393ffc1023af9a97b4b2afea2d12001fe34358b1dbc6e7670a5d93fb04fc1c0a328faa153c016a129443583ca4b67181b3102ed9a6ec626a0de37f8060babf1aa0b37c5371d77b054fab9b595e1289576986b998cb479ed6096aa90e4d12cbcd900732ad27224c920da4d451e2e34b3c9224afc0176cfb704ab4044b6a72720ae3c0d604fe2b25831f5962367629006cb6b3564b3354c185239adeeca856dbb4e88aadfdbba30096bc5ebc1bb7ac9765707b7c482cf7e3544dbeea2eb72d13b8360f9d0

spotify:
  redirect:
    url: ${SPOTIFY_REDIRECT_URL}
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_SECRET}
  token:
    refresh-buffer-seconds: 300 #5분
  mock:
    url: https://fa219561-d55d-4fba-b80a-2d4e0b46c946.mock.pstmn.io


recommendation:
  refresh-threshold: 5
  size: 20
  max-attempts: 20
  seed-max: 5
  redis:
    key-prefix: "recommendation:"
    failed-tasks-key: "recommendation:failed-refresh"
    cache-ttl-hours: 24
    failed-tasks-ttl-hours: 24

lock:
  key-prefix: "recommendation:lock:"
  wait-time: 5                    # 대기 시간
  lease-time: 10                  # 점유 시간
  max-attempts: 3                 # 최대 재시도 횟수
  initial-back-off-ms: 1000       # 초기 대기 시간
  back-off-multiplier: 2.0        # 백오프 승수
  background:
    max-attempts: 2
    initial-back-off-ms: 500
    back_-ff-multiplier: 2.0

async:
  recommendation:
    core-pool-size: 5         # 스레드 풀이 항상 유지하는 기본 스레드 수
    max-pool-size: 10         # 스레드 풀이 가질 수 있는 최대 스레드 수 -> 대기열 가득 찼을 때만 core-pool-size를 넘어 생성
    queue-capacity: 100       # 작업 대기열 크기
    keep-alive-seconds: 60    # 유휴 스레드 유지 시간


server:
  port: 9090
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    #url: jdbc:h2:mem:test;MODE=MySQL
    url: jdbc:h2:tcp://localhost/~/firstbeatDemo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    com.my.firstbeat: DEBUG
  file:
    name: ./logs/application.log